### ISSUE TITLE
Legend Arceus model preview

### ISSUE THREAD

**Issue by Corike** [KillzXGaming/Switch-Toolbox#476] opened 2022-03-26 17:54 UTC
Is it possible to add preview to trmdl files from legend arceus models?

**Comment by KillzXGaming** [comment] 2022-03-26 19:22
This has been asked alot but I personally just don't have any motivation to mess with that game atm. Anyone can do a PR though if interested.

Anyways dupe of https://github.com/KillzXGaming/Switch-Toolbox/issues/443

**Closed by KillzXGaming** 2022-03-26 19:22 UTC
