### ISSUE TITLE
Some models found in BFRES files don't T-Pose well

### ISSUE THREAD

**Issue by AtomicLugia** [KillzXGaming/Switch-Toolbox#182] opened 2020-01-28 16:59 UTC
While I was looking for models in Go Vacation, I found them in "Romfs/Bec/". These are models of the activities (maps, outfits, etc). While I can open them just fine and even their animations work wonderfully with all of them (even with if the animation is from another activity than the model itself). Some models doesn't seem to have the T-Pose, while some do have T-Pose. I uploaded an image with this issue. Left shows them all in Rest Pose, right shows an animation played with these models. Is it possible to have an option to save the model with the current pose (like a frame of the animation) or a pseudo T-Pose? When I import them into Blender, they're pretty much useless with their different "T-Poses". I also added the BFRES file containing these models to check out for yourself.
![ynotpose](https://user-images.githubusercontent.com/60356606/73286263-8b6b1600-41f7-11ea-8280-3f658674a1b3.jpg)

[SkiJ.zip](https://github.com/KillzXGaming/Switch-Toolbox/files/4123577/SkiJ.zip)

**Comment by KillzXGaming** [comment] 2020-01-29 01:07
It's not a bug. Some developers like to use A poses, some do T poses. I could implement a pose option but it sounds easier to implement animation support for dae which is planned. Rigging and animations are all shaders for the tool so i can't easily export it as is.

**Comment by KillzXGaming** [comment] 2020-01-29 21:22
I'll close this since i don't think it's an issue with the toolbox. Poses should be fairly simple to alter in a 3d program and i'll have dae animations at some point for keeping animation poses.

**Closed by KillzXGaming** 2020-01-29 21:22 UTC

**Comment by AtomicLugia** [comment] 2020-01-31 11:23
The problem is, that isn't really an A pose since one leg is a bit off, basically all bones are a little bit off which makes it insanely difficult to turn into T pose in Blender. Is there a way to just apply a pose of the T Pose model to a model with the different rest pose in Blender? Just copying the pose in Pose mode didn't work, I already tried it. (both fixing and not fixing leaf bones while importing DAE)

Here are the DAE files, freshly exported from Switch Toolbox:
[SCUBA gear.zip](https://github.com/KillzXGaming/Switch-Toolbox/files/4139054/SCUBA.gear.zip)

**Comment by AtomicLugia** [comment] 2020-02-18 12:31
It could also work to just make an option to "copy" the reset pose of a model to another and automatically applying it so that they can be exported as DAE with the correct T-Pose.

**Comment by KillzXGaming** [comment] 2020-02-18 22:57
I am not sure if I understand what you mean. The base position has to be correct, unless you mean the skeleton animation itself? Also keep in mind that bone rotations are bugged with blender atm https://github.com/KillzXGaming/Switch-Toolbox/issues/175
